"""empty message

Revision ID: fe72f45f0388
Revises: 
Create Date: 2023-03-05 22:25:31.868597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe72f45f0388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_neighbours')
    op.drop_table('countries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('countries_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cca', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('capital', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subregion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('area', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('map_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('population', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('flag_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='countries_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('country_neighbours',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('neighbour_country_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='country_neighbours_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='country_neighbours_pkey')
    )
    # ### end Alembic commands ###
